### ISSUE TITLE
playAdNow requesting wrong URL

### ISSUE THREAD

**Issue by jrobertojunior** [kaltura/playkit-js#616]
##### Prerequisites

- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js/issues): **yes**
- [x] Which Player [version](https://github.com/kaltura/playkit-js/releases) are you using: **playkit-js with IMA plugin**
- [x] Can you reproduce the issue with our latest release version: **yes**
- [x] Can you reproduce the issue with the latest code from master: **yes**
- [x] What browser and OS names and versions are you using: **Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (x86_64), macOS Version 11.6**
- [x] If applicable, add test code or test page to reproduce: [follow this link](https://api.livecommerce.tupi.io/front), click on "connect", then "broadcast" button. Watch the console for the output.

```js
console.log("-> " + vastTagUrl);
kalturaPlayer.ads.playAdNow([{ url: [vastTagUrl] }]);
```

##### Expected behavior

Player should display the ad that's defined in the VAST tag, addressed by the URL stored in `vastTagUrl`.

##### Actual behavior

The requests are made for the URL `https://imasdk.googleapis.com` before the actual VAST tag's URL.

For example, if my URL is `https://www.foo.com/bar`, the `playAdNow` method ends up requesting for `https://imasdk.googleapis.com/www.foo.com/bar`

When I test it locally, this problem does not happen, and the ad gets displayed as it should be. Only after I deploy de website that the IMA requests prepends this URL before the ad's URL.

It's worth mentioning that, even if the ad is correctly displayed locally, when I click it, it's expected to redirect me to the URL defined in the VAST tag (inside `NonLinearClickThrough` tags), but the URL gets prepended by the same `https://imasdk.googleapis.com`. I believe the cause is the same as the problem I mentioned before, since the behavior is equal.

##### Console output

```
-> https:/api.livecommerce.tupi.io/files/1638542130779.xml
bridge3.490.0_en.html:370 GET https://imasdk.googleapis.com/api.livecommerce.tupi.io/files/1638542130779.xml 404
Ly @ bridge3.490.0_en.html:370
(anonymous) @ bridge3.490.0_en.html:386
Cz @ bridge3.490.0_en.html:384
Bz @ bridge3.490.0_en.html:383
Az.get @ bridge3.490.0_en.html:382
$U @ bridge3.490.0_en.html:926
(anonymous) @ bridge3.490.0_en.html:926
nM.I @ bridge3.490.0_en.html:643
Kh @ bridge3.490.0_en.html:113
G @ bridge3.490.0_en.html:112
kO @ bridge3.490.0_en.html:708
gO.I @ bridge3.490.0_en.html:707
Gh @ bridge3.490.0_en.html:111
b @ bridge3.490.0_en.html:109
```

**Comment by kaltura-hooks** [comment]
Hi @jrobertojunior,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by yairans** [comment]
@jrobertojunior I think you missed '/' in the ad url. 
You send https:/api.livecommerce.tupi.io/files/1638542130779.xml. 
It should be https://api.livecommerce.tupi.io/files/1638542130779.xml

**Comment by jrobertojunior** [comment]
Thank you for the fast response.

The URL was wrong, after I added the missing '/' everything worked as expected.

Huge thanks! I'm closing the issue now.
